version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: appointments
      POSTGRES_PASSWORD: appointments
    ports:
      - 5432:5432
  app:
    image: alex-vladut/appointments
    container_name: alex-vladut-appointments
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/appointments
    ports:
      - 8080:8080
    depends_on:
      - db