version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: appointments
      POSTGRES_PASSWORD: appointments
    ports:
      - 5432:5432
  app:
    build: .
    container_name: alex-vladut-appointments
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    ports:
      - 8080:8080
