spring:
  application:
    name: appointments
  datasource:
    url: "jdbc:postgresql://localhost:5432/appointments"
    username: "postgres"
    password: "postgres"
  flyway:
    locations: "classpath:/db/migration"