spring:
  application:
    name: appointments
  datasource:
    url: "jdbc:postgresql://localhost:5432/appointments"
    username: "appointments"
    password: "appointments"
  jpa:
    show-sql: true
  flyway:
    password: ${spring.datasource.username}
    user: ${spring.datasource.username}